import { Injectable } from '@angular/core';
import { Students } from '../models/students';
import { BehaviorSubject } from 'rxjs';


@Injectable({
  providedIn: 'root'
})
export class StudentsService {
 public students: Students[]= 
  [
    {
      "id": 1,
      "firstname": "aBehara",
      "middlename": "Teja",
      "lastname": "Prasad",
      "gender": "Male",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara@gmail.com",
      "image": "gsdgsdg",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    },
    {
      "id": 2,
      "firstname": "Behara2",
      "middlename": "Teja2",
      "lastname": "Prasad2",
      "gender": "Male2",
      "dob": new Date("17/06/1995"),
      "joinDate": new Date("17/06/1995"),
      "email": "tejaprasadbehara2@gmail.com",
      "image": "gsdgsdg2",
      "classs": 1,
      "section": "A"
    }
  ];

  private studentsJsonData = new BehaviorSubject<any>(null);
  public studentsJson = this.studentsJsonData.asObservable();
  
  constructor() { }
  public  getStudents() {
  // console.log(this.students)
    this.studentsJsonData.next(this.students);    
  }
}
